### PR TITLE
Property as Codable

### PR DESCRIPTION
**Pull request by johanneskares**
Make Property conform to the Codable protocol.

### CODE REVIEW

**Comment by johanneskares** [comment]
Any chance of getting this in, for now maintaining a copy of Property in my code

**Comment by johanneskares** [comment]
Any chance that this will be merged in?

For now maintaining a copy of Property in my code.

**Comment by tonyarnold** [comment]
> Any chance that this will be merged in?

Yes, sorry - we're all a little tied up with other things at the moment but the PR is very appreciated - thank you!

Any chance you could add a couple of basic tests for this change? In theory it looks fine to me, but I'd be happier if we had some kind of coverage here.

**Comment by johanneskares** [comment]
Hey Tony, added a simple test that decodes and encodes a Property.

**Comment by tonyarnold** [comment]
Thanks, @johanneskares! 

Does this require that the value the Property wraps has to conform to `Codable` as well? I'm not sure that's something we want to force on users of the library.

Sorry to throw a curve ball after sounding so positive about the changes, but I wonder if this might be better framed as a type constrained extension on `Property` and `AnyProperty`?

**Comment by johanneskares** [comment]
Hey @tonyarnold ,

so I was finally able to solve this. Unfortunately, the constrained extension approach didn't work, because `required convenience` initializers don't work with extensions.

I was however able to remove to constraint of the wrapped value needing to conform to the Codable protocol. If the value doesn't conform, it will just throw a runtime error during either encoding or decoding.

**Comment by johanneskares** [comment]
@tonyarnold ,

any chance of having this merged in with the recent updates?

**Comment by johanneskares** [comment]
@tonyarnold Any updates on this?

**Comment by srdanrasic** [comment]
Hi @johanneskares,

Thanks for suggesting this. I'm not sure I would recommend doing it though. The problem is that Property is not a value type nor a type that has value semantics. This makes full conformation to Codable impossible - how would you encode all active observers? It can't be done.

I'm sure your implementation works for your case and would work for some other peoples cases, but in general this is not a recommended practice. I'll close the PR, but I really appreciate your effort.

**Pull request closed without merging**
