### PR TITLE
Bump version in podspec

### PR DESCRIPTION
**Pull request by dcacenabes**
Bump the version definition in the podspec to the latest one 3.19.0

### CODE REVIEW

**Comment by Goktug** [comment]
Please prioritize this because we had to fork the library to be able to use the latest version of the library and **our top crash** in Glovo causes by the bugs that you already fixed in the `3.18.3` and `3.18.4` versions.

**Review by Goktug — APPROVED** [review]

**Comment by srdanrasic** [comment]
Thanks guys, I'll make a release 🙌

**Comment by dcacenabes** [comment]
Thank you @srdanrasic !

**Comment by Goktug** [comment]
Hey @srdanrasic, thank you for handling the new release. If you don't mind, could you provide a date for it, please?

**Comment by srdanrasic** [comment]
@Goktug I though I had made the release, but I might have made a mistake. Can you try again?

**Pull request merged**
